### ISSUE TITLE
Host mode does not work on Linux.

### ISSUE THREAD

**Issue by walle303** [spacechase0/StardewValleyMP#42]
Host mode does not work in the Linux version of Stardew Valley

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'TcpListener.Create' not found.
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x40eb72f0 + 0x00083> in <filename unknown>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x40eb6e10 + 0x001f5> in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x40eb6c20 + 0x00023> in <filename unknown>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x40eb6b60 + 0x0005b> in <filename unknown>:0 
  at System.Threading.ThreadHelper.ThreadStart () <0x40eb6a20 + 0x0002f> in <filename unknown>:0 
AL lib: (EE) alc_cleanup: 1 device not closed
```

This appears to be similar to the following bug: https://bugzilla.xamarin.com/show_bug.cgi?id=38167

**Comment by spacechase0** [comment]
Huh. That's weird.

What version of Mono are you using?

**Comment by walle303** [comment]
The system version I have installed is

```
Mono JIT compiler version 4.6.1 (Stable 4.6.1.3/abb06f1 Mon Oct  3 07:51:42 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
However, Steam/Stardew may have its own version.

Kernel Version:
`Linux Manjaro 4.9.0-1-MANJARO #1 SMP PREEMPT Sun Nov 27 23:57:02 UTC 2016 x86_64 GNU/Linux`

**Comment by dandels** [comment]
Worked for me on Arch Linux when I changed "TcpListener.Create(port)" to "new TcpListener(IPAddress.Any, port)" in Multiplayer.cs.

**Comment by spacechase0** [comment]
Yes, but that isn't a good solution. See #44

**Comment by spacechase0** [comment]
I believe platform issues are fixed in the current master, although I'd appreciate it being tested.

**Comment by RobertZenz** [comment]
I'm still seeing the same with 2.12 and the builtin Mono of the GOG version (which should be 4.6).
